<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-06-05 at 04:31:57.
 */
include('../../modelo/Workflow.class.php');
class WorkflowUsuarioTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WorkflowUsuario
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WorkflowUsuario;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert ("Administrador") == true.
     *
     * @covers WorkflowUsuario::poseeRol
     */
    public function testPoseeRol() {
        $this->assertEquals(
                true
                , $this->object->poseeRol("Administrador")
        );
    }

    /**
     * @covers WorkflowUsuario::setNombre
     * @todo   Implement testSetNombre().
     */
    public function testSetNombre() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::getNombre
     * @todo   Implement testGetNombre().
     */
    public function testGetNombre() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::setIdUsuario
     * @todo   Implement testSetIdUsuario().
     */
    public function testSetIdUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::getIdUsuario
     * @todo   Implement testGetIdUsuario().
     */
    public function testGetIdUsuario() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::addRol
     * @todo   Implement testAddRol().
     */
    public function testAddRol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::getMetodoLogin
     * @todo   Implement testGetMetodoLogin().
     */
    public function testGetMetodoLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::setEmail
     * @todo   Implement testSetEmail().
     */
    public function testSetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::setMetodoLogin
     * @todo   Implement testSetMetodoLogin().
     */
    public function testSetMetodoLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::getRoles
     * @todo   Implement testGetRoles().
     */
    public function testGetRoles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::getEstado
     * @todo   Implement testGetEstado().
     */
    public function testGetEstado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::getIdSec
     * @todo   Implement testGetIdSec().
     */
    public function testGetIdSec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::setEstado
     * @todo   Implement testSetEstado().
     */
    public function testSetEstado() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WorkflowUsuario::setIdSec
     * @todo   Implement testSetIdSec().
     */
    public function testSetIdSec() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
